global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/<webhook-id>'

route:
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
  - receiver: 'slack-notifications'
    continue: true
  - receiver: default-telegram

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ range .Alerts -}}
      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

      *Description:* {{ .Annotations.description }}

      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}

- name: default-telegram
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11" # Placeholder token
    chat_id: 123456789 # Phải là số nguyên (int64) khác 0 để tránh lỗi parse config
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""
